/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthenticatedKeysRouteImport } from './routes/_authenticated/keys'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFilesIndexRouteImport } from './routes/_authenticated/files/index'
import { Route as AuthenticatedFilesFileIdRouteImport } from './routes/_authenticated/files/$fileId'
import { Route as ApiPublicSyncUploadRouteImport } from './routes/api/public/sync/upload'
import { Route as ApiPublicSyncSignaturesRouteImport } from './routes/api/public/sync/signatures'
import { Route as ApiPublicSyncNegotiateRouteImport } from './routes/api/public/sync/negotiate'
import { Route as ApiPublicSyncFilesRouteImport } from './routes/api/public/sync/files'
import { Route as ApiPublicSyncDownloadRouteImport } from './routes/api/public/sync/download'
import { Route as ApiPublicSyncCommitRouteImport } from './routes/api/public/sync/commit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKeysRoute = AuthenticatedKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFilesIndexRoute = AuthenticatedFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFilesFileIdRoute =
  AuthenticatedFilesFileIdRouteImport.update({
    id: '/files/$fileId',
    path: '/files/$fileId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicSyncUploadRoute = ApiPublicSyncUploadRouteImport.update({
  id: '/api/public/sync/upload',
  path: '/api/public/sync/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncSignaturesRoute = ApiPublicSyncSignaturesRouteImport.update({
  id: '/api/public/sync/signatures',
  path: '/api/public/sync/signatures',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncNegotiateRoute = ApiPublicSyncNegotiateRouteImport.update({
  id: '/api/public/sync/negotiate',
  path: '/api/public/sync/negotiate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncFilesRoute = ApiPublicSyncFilesRouteImport.update({
  id: '/api/public/sync/files',
  path: '/api/public/sync/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncDownloadRoute = ApiPublicSyncDownloadRouteImport.update({
  id: '/api/public/sync/download',
  path: '/api/public/sync/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncCommitRoute = ApiPublicSyncCommitRouteImport.update({
  id: '/api/public/sync/commit',
  path: '/api/public/sync/commit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/api/health': typeof ApiHealthRoute
  '/files/$fileId': typeof AuthenticatedFilesFileIdRoute
  '/files/': typeof AuthenticatedFilesIndexRoute
  '/api/public/sync/commit': typeof ApiPublicSyncCommitRoute
  '/api/public/sync/download': typeof ApiPublicSyncDownloadRoute
  '/api/public/sync/files': typeof ApiPublicSyncFilesRoute
  '/api/public/sync/negotiate': typeof ApiPublicSyncNegotiateRoute
  '/api/public/sync/signatures': typeof ApiPublicSyncSignaturesRoute
  '/api/public/sync/upload': typeof ApiPublicSyncUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/api/health': typeof ApiHealthRoute
  '/files/$fileId': typeof AuthenticatedFilesFileIdRoute
  '/files': typeof AuthenticatedFilesIndexRoute
  '/api/public/sync/commit': typeof ApiPublicSyncCommitRoute
  '/api/public/sync/download': typeof ApiPublicSyncDownloadRoute
  '/api/public/sync/files': typeof ApiPublicSyncFilesRoute
  '/api/public/sync/negotiate': typeof ApiPublicSyncNegotiateRoute
  '/api/public/sync/signatures': typeof ApiPublicSyncSignaturesRoute
  '/api/public/sync/upload': typeof ApiPublicSyncUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/keys': typeof AuthenticatedKeysRoute
  '/api/health': typeof ApiHealthRoute
  '/_authenticated/files/$fileId': typeof AuthenticatedFilesFileIdRoute
  '/_authenticated/files/': typeof AuthenticatedFilesIndexRoute
  '/api/public/sync/commit': typeof ApiPublicSyncCommitRoute
  '/api/public/sync/download': typeof ApiPublicSyncDownloadRoute
  '/api/public/sync/files': typeof ApiPublicSyncFilesRoute
  '/api/public/sync/negotiate': typeof ApiPublicSyncNegotiateRoute
  '/api/public/sync/signatures': typeof ApiPublicSyncSignaturesRoute
  '/api/public/sync/upload': typeof ApiPublicSyncUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/login'
    | '/playground'
    | '/sitemap.xml'
    | '/dashboard'
    | '/jobs'
    | '/keys'
    | '/api/health'
    | '/files/$fileId'
    | '/files/'
    | '/api/public/sync/commit'
    | '/api/public/sync/download'
    | '/api/public/sync/files'
    | '/api/public/sync/negotiate'
    | '/api/public/sync/signatures'
    | '/api/public/sync/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/login'
    | '/playground'
    | '/sitemap.xml'
    | '/dashboard'
    | '/jobs'
    | '/keys'
    | '/api/health'
    | '/files/$fileId'
    | '/files'
    | '/api/public/sync/commit'
    | '/api/public/sync/download'
    | '/api/public/sync/files'
    | '/api/public/sync/negotiate'
    | '/api/public/sync/signatures'
    | '/api/public/sync/upload'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/docs'
    | '/login'
    | '/playground'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/jobs'
    | '/_authenticated/keys'
    | '/api/health'
    | '/_authenticated/files/$fileId'
    | '/_authenticated/files/'
    | '/api/public/sync/commit'
    | '/api/public/sync/download'
    | '/api/public/sync/files'
    | '/api/public/sync/negotiate'
    | '/api/public/sync/signatures'
    | '/api/public/sync/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  PlaygroundRoute: typeof PlaygroundRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPublicSyncCommitRoute: typeof ApiPublicSyncCommitRoute
  ApiPublicSyncDownloadRoute: typeof ApiPublicSyncDownloadRoute
  ApiPublicSyncFilesRoute: typeof ApiPublicSyncFilesRoute
  ApiPublicSyncNegotiateRoute: typeof ApiPublicSyncNegotiateRoute
  ApiPublicSyncSignaturesRoute: typeof ApiPublicSyncSignaturesRoute
  ApiPublicSyncUploadRoute: typeof ApiPublicSyncUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/keys': {
      id: '/_authenticated/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AuthenticatedKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/files/': {
      id: '/_authenticated/files/'
      path: '/files'
      fullPath: '/files/'
      preLoaderRoute: typeof AuthenticatedFilesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/files/$fileId': {
      id: '/_authenticated/files/$fileId'
      path: '/files/$fileId'
      fullPath: '/files/$fileId'
      preLoaderRoute: typeof AuthenticatedFilesFileIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/sync/upload': {
      id: '/api/public/sync/upload'
      path: '/api/public/sync/upload'
      fullPath: '/api/public/sync/upload'
      preLoaderRoute: typeof ApiPublicSyncUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/signatures': {
      id: '/api/public/sync/signatures'
      path: '/api/public/sync/signatures'
      fullPath: '/api/public/sync/signatures'
      preLoaderRoute: typeof ApiPublicSyncSignaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/negotiate': {
      id: '/api/public/sync/negotiate'
      path: '/api/public/sync/negotiate'
      fullPath: '/api/public/sync/negotiate'
      preLoaderRoute: typeof ApiPublicSyncNegotiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/files': {
      id: '/api/public/sync/files'
      path: '/api/public/sync/files'
      fullPath: '/api/public/sync/files'
      preLoaderRoute: typeof ApiPublicSyncFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/download': {
      id: '/api/public/sync/download'
      path: '/api/public/sync/download'
      fullPath: '/api/public/sync/download'
      preLoaderRoute: typeof ApiPublicSyncDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/commit': {
      id: '/api/public/sync/commit'
      path: '/api/public/sync/commit'
      fullPath: '/api/public/sync/commit'
      preLoaderRoute: typeof ApiPublicSyncCommitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedKeysRoute: typeof AuthenticatedKeysRoute
  AuthenticatedFilesFileIdRoute: typeof AuthenticatedFilesFileIdRoute
  AuthenticatedFilesIndexRoute: typeof AuthenticatedFilesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedKeysRoute: AuthenticatedKeysRoute,
  AuthenticatedFilesFileIdRoute: AuthenticatedFilesFileIdRoute,
  AuthenticatedFilesIndexRoute: AuthenticatedFilesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  PlaygroundRoute: PlaygroundRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPublicSyncCommitRoute: ApiPublicSyncCommitRoute,
  ApiPublicSyncDownloadRoute: ApiPublicSyncDownloadRoute,
  ApiPublicSyncFilesRoute: ApiPublicSyncFilesRoute,
  ApiPublicSyncNegotiateRoute: ApiPublicSyncNegotiateRoute,
  ApiPublicSyncSignaturesRoute: ApiPublicSyncSignaturesRoute,
  ApiPublicSyncUploadRoute: ApiPublicSyncUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
